const DEFAULT_INTERVAL = 15;
const alarmName = id => `WPCM_${id}`;
const normalizeText = value => String(value || "").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/\s+/g," ").trim();
function simpleHash(input){let hash=2166136261;for(const ch of String(input||"")){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,"0")}
function firstDifference(before,after){const a=String(before||""),b=String(after||"");let i=0,max=Math.min(a.length,b.length);while(i<max&&a[i]===b[i])i++;const start=Math.max(0,i-70);return{before:a.slice(start,Math.min(a.length,i+170)),after:b.slice(start,Math.min(b.length,i+170))}}
async function getWatches(){const s=await chrome.storage.local.get({watches:[]});return Array.isArray(s.watches)?s.watches:[]}
const saveWatches=watches=>chrome.storage.local.set({watches});
async function notify(title,message){await chrome.notifications.create({type:"basic",iconUrl:"icon128.png",title,message:String(message||"").slice(0,240)})}
const exactUrl=value=>String(value||"").split("#")[0];
async function findOpenTab(url){const target=exactUrl(url),tabs=await chrome.tabs.query({});return tabs.find(tab=>tab.id&&exactUrl(tab.url)===target)||null}
async function fetchPublicPage(url){const r=await fetch(url,{cache:"no-store",credentials:"omit",redirect:"follow"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const type=r.headers.get("content-type")||"";if(!type.includes("text/")&&!type.includes("html"))throw new Error("Unsupported content type");return{text:normalizeText(await r.text()).slice(0,300000),source:"fetch"}}
async function captureWatch(watch){const tab=await findOpenTab(watch.url);if(watch.mode==="element"){if(!tab?.id)throw new Error("Selected-element monitoring requires this exact page to remain open in a Chrome tab.");const result=await chrome.tabs.sendMessage(tab.id,{type:"WPCM_CAPTURE_ELEMENT",selector:watch.selector});if(!result?.ok)throw new Error(result?.error||"Selected element could not be read.");return{text:String(result.text||"").slice(0,200000),source:"selected-element"}}if(tab?.id){try{const rendered=await chrome.tabs.sendMessage(tab.id,{type:"WPCM_CAPTURE_PAGE"});if(rendered?.ok&&typeof rendered.text==="string")return{text:rendered.text.slice(0,300000),source:"open-tab"}}catch{}}return fetchPublicPage(watch.url)}
async function ensureAlarm(watch){if(!watch.enabled){await chrome.alarms.clear(alarmName(watch.id));return}const minutes=Math.max(5,Number(watch.intervalMinutes||DEFAULT_INTERVAL)),current=await chrome.alarms.get(alarmName(watch.id));if(current&&Math.round(Number(current.periodInMinutes||0))===minutes)return;await chrome.alarms.clear(alarmName(watch.id));await chrome.alarms.create(alarmName(watch.id),{delayInMinutes:minutes,periodInMinutes:minutes})}
async function ensureAllAlarms(){const watches=await getWatches(),alarms=await chrome.alarms.getAll();for(const alarm of alarms){if(!alarm.name.startsWith("WPCM_"))continue;const id=alarm.name.slice(5);if(!watches.some(w=>String(w.id)===id&&w.enabled))await chrome.alarms.clear(alarm.name)}for(const watch of watches)await ensureAlarm(watch)}
function evaluatePhraseMode(watch,text){const phrase=String(watch.phrase||"").trim(),contains=text.toLocaleLowerCase().includes(phrase.toLocaleLowerCase()),previous=typeof watch.lastPhraseState==="boolean"?watch.lastPhraseState:null;return{contains,changed:previous!==null&&previous!==contains,reason:previous!==null&&previous!==contains?(contains?`Text appeared: "${phrase}"`:`Text disappeared: "${phrase}"`):""}}
async function checkWatchById(id,manual=false){const watches=await getWatches(),index=watches.findIndex(w=>String(w.id)===String(id));if(index<0)return{ok:false,reason:"watch-not-found"};const watch=watches[index];if(!watch.enabled&&!manual)return{ok:false,reason:"watch-disabled"};const startedAt=Date.now();try{const capture=await captureWatch(watch),text=String(capture.text||""),nextHash=simpleHash(text),previousHash=watch.lastHash||null,previousSample=String(watch.lastSample||"");let changed=false,reason="",nextPhraseState=watch.lastPhraseState;if(watch.mode==="phrase"){const r=evaluatePhraseMode(watch,text);changed=r.changed;reason=r.reason;nextPhraseState=r.contains}else if(previousHash&&previousHash!==nextHash){changed=true;reason=watch.mode==="element"?"Selected element changed.":"Page content changed."}const now=Date.now(),nextSample=text.slice(0,5000),diff=changed?firstDifference(previousSample,nextSample):{before:"",after:""};let history=Array.isArray(watch.history)?watch.history:[];if(changed)history=[{at:now,reason,before:diff.before.slice(0,260),after:diff.after.slice(0,260)},...history].slice(0,10);watches[index]={...watch,lastHash:nextHash,lastPhraseState:nextPhraseState,lastSample:nextSample,lastCheckedAt:now,lastChangedAt:changed?now:watch.lastChangedAt||null,lastError:null,lastSource:capture.source,lastCheckDurationMs:Date.now()-startedAt,history};await saveWatches(watches);if(changed)await notify(`Page changed: ${watch.title||watch.url}`,`${reason}${diff.after?` New: ${diff.after}`:""}`);return{ok:true,changed,reason,checkedAt:now,hash:nextHash,source:capture.source}}catch(error){watches[index]={...watch,lastCheckedAt:Date.now(),lastError:String(error?.message||error),lastCheckDurationMs:Date.now()-startedAt};await saveWatches(watches);return{ok:false,reason:"capture-failed",error:String(error?.message||error)}}}
async function resetBaseline(id){const watches=await getWatches(),index=watches.findIndex(w=>String(w.id)===String(id));if(index<0)return{ok:false,reason:"watch-not-found"};watches[index]={...watches[index],lastHash:null,lastPhraseState:null,lastSample:"",lastChangedAt:null,lastError:null,history:[]};await saveWatches(watches);return checkWatchById(id,true)}
chrome.runtime.onInstalled.addListener(()=>ensureAllAlarms().catch(()=>{}));chrome.runtime.onStartup.addListener(()=>ensureAllAlarms().catch(()=>{}));chrome.alarms.onAlarm.addListener(a=>{if(a.name.startsWith("WPCM_"))checkWatchById(a.name.slice(5),false).catch(()=>{})});chrome.storage.onChanged.addListener((changes,area)=>{if(area==="local"&&changes.watches)ensureAllAlarms().catch(()=>{})});chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message?.type==="WPCM_CHECK_NOW"){checkWatchById(message.id,true).then(sendResponse).catch(e=>sendResponse({ok:false,error:String(e)}));return true}if(message?.type==="WPCM_RESET_BASELINE"){resetBaseline(message.id).then(sendResponse).catch(e=>sendResponse({ok:false,error:String(e)}));return true}if(message?.type==="WPCM_SYNC_ALARMS"){ensureAllAlarms().then(()=>sendResponse({ok:true})).catch(e=>sendResponse({ok:false,error:String(e)}));return true}});ensureAllAlarms().catch(()=>{});
